# Generated by Django 3.2.20 on 2023-09-09 06:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date_published']},
        ),
        migrations.AddField(
            model_name='article',
            name='alerte_info',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='en_vedette',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
