# Generated by Django 4.2.5 on 2023-09-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='en_vedette',
            field=models.BooleanField(default=False),
        ),
    ]
