# Generated by Django 4.2.5 on 2023-09-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_article_options_article_is_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='alerte_info',
            field=models.BooleanField(default=False),
        ),
    ]
